/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package com.mycompany.act5_ej1;
import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.lang.NumberFormatException;
import javax.swing.JOptionPane;
/**
 *
 * @author Samuel
 */
public class VPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VPrincipal.class.getName());

    /**
     * Creates new form VPrincipal
     */
    public VPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRead = new javax.swing.JButton();
        btnCreate = new javax.swing.JButton();
        btnUpd = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        btnClearFields = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnRead.setText("Read");
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnUpd.setText("Update");
        btnUpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdActionPerformed(evt);
            }
        });

        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jLabel2.setText("Numero:");

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });

        btnClearFields.setText("Clear Fields");
        btnClearFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFieldsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtNombre))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnCreate)
                        .addGap(18, 18, 18)
                        .addComponent(btnRead)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpd)
                        .addGap(18, 18, 18)
                        .addComponent(btnDel)
                        .addGap(18, 18, 18)
                        .addComponent(btnClearFields)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRead)
                    .addComponent(btnUpd)
                    .addComponent(btnDel)
                    .addComponent(btnCreate)
                    .addComponent(btnClearFields))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        try {
            
            String newName = String.valueOf(txtNombre.getText());
            long newNumber = Long.parseLong(txtNumero.getText());
            
            String nameNumberString;
            String name;
            long number;
            int index;

            File file = new File("C:\\Users\\Samuel\\Desktop\\UNAL\\2025-2\\POO\\ACTIVIDAD 5\\Act5_Ej1\\Act5_Files\\Act5FriendsContact.txt");

            if (!file.exists()) {

                file.createNewFile();
            }


            RandomAccessFile raf = new RandomAccessFile(file, "rw");
            boolean found = false;

            while (raf.getFilePointer() < raf.length()) {

                nameNumberString = raf.readLine();

                String[] lineSplit = nameNumberString.split("!");

                name = lineSplit[0];
                number = Long.parseLong(lineSplit[1]);

                if (name == newName
                    || number == newNumber) {
                    found = true;
                    break;
                }
            }

            if (found == false) {

                nameNumberString = newName + "!"
                      + String.valueOf(newNumber);

                raf.writeBytes(nameNumberString);

                raf.writeBytes(System.lineSeparator());

                JOptionPane.showMessageDialog(null, "Friend added");
                txtNombre.setText("");
                txtNumero.setText("");
                
                raf.close();
            }
            else {

                raf.close();

                JOptionPane.showMessageDialog(null, "The contact exists");
                txtNombre.setText("");
                txtNumero.setText("");
            }
        }

        catch (IOException ioe) {

            JOptionPane.showMessageDialog(null, "An error has ocurred creating/opening the file");
            txtNombre.setText("");
            txtNumero.setText("");
        }
        catch (NumberFormatException nef) {

            JOptionPane.showMessageDialog(null, "A number format is incorrect");
            txtNombre.setText("");
            txtNumero.setText("");
        }
        
        
        
        
        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFieldsActionPerformed
        txtNombre.setText("");
        txtNumero.setText("");
    }//GEN-LAST:event_btnClearFieldsActionPerformed

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
        try {

            String nameNumberString;
            String name;
            String searchName = String.valueOf(txtNombre.getText());
            long number;
            int index;
            boolean found = false;

            File file = new File("C:\\Users\\Samuel\\Desktop\\UNAL\\2025-2\\POO\\ACTIVIDAD 5\\Act5_Ej1\\Act5_Files\\Act5FriendsContact.txt");

            if (!file.exists()) {

                file.createNewFile();
            }

            RandomAccessFile raf = new RandomAccessFile(file, "rw");

            while (raf.getFilePointer() < raf.length()) {

                nameNumberString = raf.readLine();

                String[] lineSplit = nameNumberString.split("!");

                name = lineSplit[0];
                number = Long.parseLong(lineSplit[1]);

                if (name.equals(searchName)){
                    txtNombre.setText(String.valueOf(name));
                    txtNumero.setText(String.valueOf(number));
                    found = true;
                    raf.close();
                    JOptionPane.showMessageDialog(null, "The name was found");
                    
                } 
                
                if (found == false){
                    JOptionPane.showMessageDialog(null, "The name was not found");
                    txtNombre.setText("");
                    txtNumero.setText("");
                    raf.close();
                }
                
            }   
        }
            catch (IOException ioe){
                JOptionPane.showMessageDialog(null, "An error has ocurred creating/opening the file");
                txtNombre.setText("");
                txtNumero.setText("");
                
            } catch (NumberFormatException nef){
                JOptionPane.showMessageDialog(null, "A number format is incorrect");
                txtNombre.setText("");
                txtNumero.setText("");
                
            }
    }//GEN-LAST:event_btnReadActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        try {

            String deleteName = String.valueOf(txtNombre.getText());
            long deleteNumber = Long.parseLong(txtNumero.getText());
            
            String nameNumberString;
            String name;
            long number;
            int index;

            File file = new File("C:\\Users\\Samuel\\Desktop\\UNAL\\2025-2\\POO\\ACTIVIDAD 5\\Act5_Ej1\\Act5_Files\\Act5FriendsContact.txt");

            if (file.exists() == false) {

                file.createNewFile();
            }

            RandomAccessFile raf = new RandomAccessFile(file, "rw");
            boolean found = false;

           
            while (raf.getFilePointer() < raf.length()) {

                
                nameNumberString = raf.readLine();

                
                String[] lineSplit = nameNumberString.split("!");

                name = lineSplit[0];
                number = Long.parseLong(lineSplit[1]);

                if (name.equals(deleteName)) {
                    JOptionPane.showMessageDialog(null, "The contact to delete was found");
                    
                    found = true;
                    break;
                }
            }

            if (found == true) {

                File tmpFile = new File("C:\\Users\\Samuel\\Desktop\\UNAL\\2025-2\\POO\\ACTIVIDAD 5\\Act5_Ej1\\Act5_Files\\temp.txt");

                RandomAccessFile tmpraf = new RandomAccessFile(tmpFile, "rw");
                
                raf.seek(0);

                while (raf.getFilePointer() < raf.length()) {

                    nameNumberString = raf.readLine();

                    index = nameNumberString.indexOf('!');
                    name = nameNumberString.substring(
                        0, index);

                    if (name.equals(deleteName)) {

                        continue;
                    }

                    tmpraf.writeBytes(nameNumberString);

                    tmpraf.writeBytes(
                        System.lineSeparator());
                }

                
                raf.seek(0);
                tmpraf.seek(0);

                while (tmpraf.getFilePointer() < tmpraf.length()) {
                    raf.writeBytes(tmpraf.readLine());
                    raf.writeBytes(System.lineSeparator());
                }

                raf.setLength(tmpraf.length());

                tmpraf.close();
                raf.close();

                tmpFile.delete();
                JOptionPane.showMessageDialog(null, "Contact deleted");
                txtNombre.setText("");
                txtNumero.setText("");
            }

            else {

                raf.close();
                JOptionPane.showMessageDialog(null, "The contact does not exists");
                txtNombre.setText("");
                txtNumero.setText("");
            }
        }

        catch (IOException ioe) {
            JOptionPane.showMessageDialog(null, "An error has ocurred creating/opening the file");
            txtNombre.setText("");
            txtNumero.setText("");
            
        } catch (NumberFormatException nef){
            JOptionPane.showMessageDialog(null, "A number format is incorrect");
            txtNombre.setText("");
            txtNumero.setText("");
        }
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnUpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdActionPerformed
        try {

            String newName = String.valueOf(txtNombre.getText());
            long newNumber = Long.parseLong(txtNumero.getText());

                String nameNumberString;
                String name;
                long number;
                int index;

                File file = new File("C:\\Users\\Samuel\\Desktop\\UNAL\\2025-2\\POO\\ACTIVIDAD 5\\Act5_Ej1\\Act5_Files\\Act5FriendsContact.txt");

                if (!file.exists()) {

                    file.createNewFile();
                }

                RandomAccessFile raf = new RandomAccessFile(file, "rw");
                boolean found = false;

               
                while (raf.getFilePointer() < raf.length()) {

                    nameNumberString = raf.readLine();

                    String[] lineSplit = nameNumberString.split("!");

                    name = lineSplit[0];
                    number = Long.parseLong(lineSplit[1]);

                    if (name.equals(newName)|| number == newNumber) {
                        found = true;
                        break;
                    }
                }

                if (found == true) {

                    File tmpFile = new File("temp.txt");

                    RandomAccessFile tmpraf = new RandomAccessFile(tmpFile, "rw");

                    raf.seek(0);

                    while (raf.getFilePointer() < raf.length()) {

                        nameNumberString = raf.readLine();

                        index = nameNumberString.indexOf('!');
                        name = nameNumberString.substring(0, index);

                        if (name.equals(newName)) {

                            nameNumberString = name + "!" + String.valueOf(newNumber);
                        }

                        tmpraf.writeBytes(nameNumberString);

                        tmpraf.writeBytes(
                            System.lineSeparator());
                    }

                    raf.seek(0);
                    tmpraf.seek(0);

                    while (tmpraf.getFilePointer() < tmpraf.length()) {
                        raf.writeBytes(tmpraf.readLine());
                        raf.writeBytes(System.lineSeparator());
                    }

                    raf.setLength(tmpraf.length());

                    tmpraf.close();
                    raf.close();

                    tmpFile.delete();

                    JOptionPane.showMessageDialog(null, "Contact updated");
                    txtNombre.setText("");
                    txtNumero.setText("");
                }

                else {

                    raf.close();

                    JOptionPane.showMessageDialog(null, "The contact does not exists");
                    txtNombre.setText("");
                    txtNumero.setText("");
                }
            }

            catch (IOException ioe) {
            JOptionPane.showMessageDialog(null, "An error has ocurred creating/opening the file");
            txtNombre.setText("");
            txtNumero.setText("");
            }

            catch (NumberFormatException nef) {
            JOptionPane.showMessageDialog(null, "A number format is incorrect");
            txtNombre.setText("");
            txtNumero.setText("");
            }




        
        
        
        
    }//GEN-LAST:event_btnUpdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearFields;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnUpd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
